services:
  phonebook:
    build:
      context: .
      no_cache: true
      args:
        - BUILD_CONFIGURATION=development
    restart: always
    ports:
    - "4200:80"
    - "3000:3000"
    volumes:
      - database_directory:/database_directory
volumes:
  database_directory:

